'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Balanza.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;TextosFijos&quot;1|DATE:|
        '''&quot;TextosFijos&quot;2|VALID:|
        '''&quot;TextosFijos&quot;3|WT   (kg)UNITS|
        '''&quot;TextosFijos&quot;4|$/kg $/U|
        '''&quot;TextosFijos&quot;5|TOTAL($)|
        '''&quot;TextosFijos&quot;6|DATE:|
        '''&quot;TextosFijos&quot;7|TIME:|
        '''&quot;TextosFijos&quot;8|WT  (kg) WT (U)|
        '''&quot;TextosFijos&quot;9|TOTAL($)|
        '''&quot;TextosFijos&quot;10|Gracias por su visita|
        '''&quot;TextosFijos&quot;11|*******************************|
        '''&quot;TextosFijos&quot;12|PYMT($)|
        '''&quot;TextosFijos&quot;13|CHANGE($)|
        '''&quot;TextosFijos&quot;14|******** RECEIPT COPY *********|
        '''&quot;TextosFijos&quot;15|TOTAL      ART.|
        '''&quot;TextosFijos&quot;16|ART.|
        '''&quot;TextosFijos&quot;17|kg        [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property Resto() As String
            Get
                Return ResourceManager.GetString("Resto", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
